export { scan, scanSingleFile } from "./scanner.js";
export { writeSidecarFile, buildSidecarMarkdown, generateSidecarPath } from "./markdown.js";
export { getMimeType, getExtractor } from "./extractors/index.js";
export { FileCache } from "./cache.js";
export { loadConfig, mergeConfigWithOptions } from "./config.js";
export { getStatus } from "./status.js";
export type { StatusResult } from "./status.js";
export { resolveProvider } from "./providers/index.js";
export { summarizeFiles, summarizeSingle } from "./summarizer.js";
export type { SummaryProvider, SummaryRequest, SummaryResult } from "./providers/types.js";
export { createTikaExtractor, isTikaAvailable } from "./extractors/tika.js";
export { ensureTika, stopTika } from "./tika-lifecycle.js";
export { initGitIntegration, isGitRepo, getGitRoot } from "./git.js";
export type { InitResult } from "./git.js";
export { generateIndexes, INDEX_FILENAME } from "./indexer.js";
export { cleanSidecars } from "./clean.js";
export type { CleanResult } from "./clean.js";
export type { ExtractedFile, ScanOptions, ScanResult, SidecarMetadata, FileMetadata } from "./types.js";
export type { Extractor, ExtractionResult } from "./extractors/types.js";
